// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: allowlist.sql

package database

import (
	"context"
)

const getAllIPAllowList = `-- name: GetAllIPAllowList :many
SELECT subnet FROM ip_allowlist
`

func (q *Queries) GetAllIPAllowList(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAllIPAllowList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subnet string
		if err := rows.Scan(&subnet); err != nil {
			return nil, err
		}
		items = append(items, subnet)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIPAllowList = `-- name: RemoveIPAllowList :exec
DELETE FROM ip_allowlist
    WHERE subnet = ?1
`

func (q *Queries) RemoveIPAllowList(ctx context.Context, db DBTX, subnet string) error {
	_, err := db.ExecContext(ctx, removeIPAllowList, subnet)
	return err
}

const upsertIPAllowList = `-- name: UpsertIPAllowList :exec
INSERT INTO ip_allowlist (subnet)
    VALUES (?1)
    ON CONFLICT (subnet) DO NOTHING
`

func (q *Queries) UpsertIPAllowList(ctx context.Context, db DBTX, subnet string) error {
	_, err := db.ExecContext(ctx, upsertIPAllowList, subnet)
	return err
}
