// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocklist.sql

package database

import (
	"context"
)

const getAllCountryBlockList = `-- name: GetAllCountryBlockList :many
SELECT country FROM country_blocklist
`

func (q *Queries) GetAllCountryBlockList(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAllCountryBlockList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var country string
		if err := rows.Scan(&country); err != nil {
			return nil, err
		}
		items = append(items, country)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCountryBlockList = `-- name: RemoveCountryBlockList :exec
DELETE FROM country_blocklist
    WHERE country = ?1
`

func (q *Queries) RemoveCountryBlockList(ctx context.Context, db DBTX, country string) error {
	_, err := db.ExecContext(ctx, removeCountryBlockList, country)
	return err
}

const upsertCountryBlockList = `-- name: UpsertCountryBlockList :exec
INSERT INTO country_blocklist (country)
    VALUES (?1)
    ON CONFLICT (country) DO NOTHING
`

func (q *Queries) UpsertCountryBlockList(ctx context.Context, db DBTX, country string) error {
	_, err := db.ExecContext(ctx, upsertCountryBlockList, country)
	return err
}
