// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: excludelist.sql

package database

import (
	"context"
)

const getAllASNExcludeList = `-- name: GetAllASNExcludeList :many
SELECT asn FROM asn_excludelist
`

func (q *Queries) GetAllASNExcludeList(ctx context.Context, db DBTX) ([]int64, error) {
	rows, err := db.QueryContext(ctx, getAllASNExcludeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var asn int64
		if err := rows.Scan(&asn); err != nil {
			return nil, err
		}
		items = append(items, asn)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDomainExcludeList = `-- name: GetAllDomainExcludeList :many
SELECT domain FROM domain_excludelist
`

func (q *Queries) GetAllDomainExcludeList(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAllDomainExcludeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllIPExcludeList = `-- name: GetAllIPExcludeList :many
SELECT subnet FROM ip_excludelist
`

func (q *Queries) GetAllIPExcludeList(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAllIPExcludeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subnet string
		if err := rows.Scan(&subnet); err != nil {
			return nil, err
		}
		items = append(items, subnet)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllJA3ExcludeList = `-- name: GetAllJA3ExcludeList :many
SELECT hash FROM ja3_excludelist
`

func (q *Queries) GetAllJA3ExcludeList(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAllJA3ExcludeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var hash string
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeASNExcludeList = `-- name: RemoveASNExcludeList :exec
DELETE FROM asn_excludelist
    WHERE asn = ?1
`

func (q *Queries) RemoveASNExcludeList(ctx context.Context, db DBTX, asn int64) error {
	_, err := db.ExecContext(ctx, removeASNExcludeList, asn)
	return err
}

const removeDomainExcludeList = `-- name: RemoveDomainExcludeList :exec
DELETE FROM domain_excludelist
    WHERE domain = ?1
`

func (q *Queries) RemoveDomainExcludeList(ctx context.Context, db DBTX, domain string) error {
	_, err := db.ExecContext(ctx, removeDomainExcludeList, domain)
	return err
}

const removeIPExcludeList = `-- name: RemoveIPExcludeList :exec
DELETE FROM ip_excludelist
    WHERE subnet = ?1
`

func (q *Queries) RemoveIPExcludeList(ctx context.Context, db DBTX, subnet string) error {
	_, err := db.ExecContext(ctx, removeIPExcludeList, subnet)
	return err
}

const removeJA3ExcludeList = `-- name: RemoveJA3ExcludeList :exec
DELETE FROM ja3_excludelist
    WHERE hash = ?1
`

func (q *Queries) RemoveJA3ExcludeList(ctx context.Context, db DBTX, hash string) error {
	_, err := db.ExecContext(ctx, removeJA3ExcludeList, hash)
	return err
}

const upsertASNExcludeList = `-- name: UpsertASNExcludeList :exec
INSERT INTO asn_excludelist (asn)
    VALUES (?1)
    ON CONFLICT (asn) DO NOTHING
`

func (q *Queries) UpsertASNExcludeList(ctx context.Context, db DBTX, asn int64) error {
	_, err := db.ExecContext(ctx, upsertASNExcludeList, asn)
	return err
}

const upsertDomainExcludeList = `-- name: UpsertDomainExcludeList :exec
INSERT INTO domain_excludelist (domain)
    VALUES (?1)
    ON CONFLICT (domain) DO NOTHING
`

func (q *Queries) UpsertDomainExcludeList(ctx context.Context, db DBTX, domain string) error {
	_, err := db.ExecContext(ctx, upsertDomainExcludeList, domain)
	return err
}

const upsertIPExcludeList = `-- name: UpsertIPExcludeList :exec
INSERT INTO ip_excludelist (subnet)
    VALUES (?1)
    ON CONFLICT (subnet) DO NOTHING
`

func (q *Queries) UpsertIPExcludeList(ctx context.Context, db DBTX, subnet string) error {
	_, err := db.ExecContext(ctx, upsertIPExcludeList, subnet)
	return err
}

const upsertJA3ExcludeList = `-- name: UpsertJA3ExcludeList :exec
INSERT INTO ja3_excludelist (hash)
    VALUES (?1)
    ON CONFLICT (hash) DO NOTHING
`

func (q *Queries) UpsertJA3ExcludeList(ctx context.Context, db DBTX, hash string) error {
	_, err := db.ExecContext(ctx, upsertJA3ExcludeList, hash)
	return err
}
