// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: includelist.sql

package database

import (
	"context"
)

const getAllASNIncludeList = `-- name: GetAllASNIncludeList :many
SELECT asn FROM asn_includelist
`

func (q *Queries) GetAllASNIncludeList(ctx context.Context, db DBTX) ([]int64, error) {
	rows, err := db.QueryContext(ctx, getAllASNIncludeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var asn int64
		if err := rows.Scan(&asn); err != nil {
			return nil, err
		}
		items = append(items, asn)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDomainIncludeList = `-- name: GetAllDomainIncludeList :many
SELECT domain FROM domain_includelist
`

func (q *Queries) GetAllDomainIncludeList(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAllDomainIncludeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllIPIncludeList = `-- name: GetAllIPIncludeList :many
SELECT subnet FROM ip_includelist
`

func (q *Queries) GetAllIPIncludeList(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAllIPIncludeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subnet string
		if err := rows.Scan(&subnet); err != nil {
			return nil, err
		}
		items = append(items, subnet)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllJA3IncludeList = `-- name: GetAllJA3IncludeList :many
SELECT hash FROM ja3_includelist
`

func (q *Queries) GetAllJA3IncludeList(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAllJA3IncludeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var hash string
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeASNIncludeList = `-- name: RemoveASNIncludeList :exec
DELETE FROM asn_includelist
    WHERE asn = ?1
`

func (q *Queries) RemoveASNIncludeList(ctx context.Context, db DBTX, asn int64) error {
	_, err := db.ExecContext(ctx, removeASNIncludeList, asn)
	return err
}

const removeDomainIncludeList = `-- name: RemoveDomainIncludeList :exec
DELETE FROM domain_includelist
    WHERE domain = ?1
`

func (q *Queries) RemoveDomainIncludeList(ctx context.Context, db DBTX, domain string) error {
	_, err := db.ExecContext(ctx, removeDomainIncludeList, domain)
	return err
}

const removeIPIncludeList = `-- name: RemoveIPIncludeList :exec
DELETE FROM ip_includelist
    WHERE subnet = ?1
`

func (q *Queries) RemoveIPIncludeList(ctx context.Context, db DBTX, subnet string) error {
	_, err := db.ExecContext(ctx, removeIPIncludeList, subnet)
	return err
}

const removeJA3IncludeList = `-- name: RemoveJA3IncludeList :exec
DELETE FROM ja3_includelist
    WHERE hash = ?1
`

func (q *Queries) RemoveJA3IncludeList(ctx context.Context, db DBTX, hash string) error {
	_, err := db.ExecContext(ctx, removeJA3IncludeList, hash)
	return err
}

const upsertASNIncludeList = `-- name: UpsertASNIncludeList :exec
INSERT INTO asn_includelist (asn)
    VALUES (?1)
    ON CONFLICT (asn) DO NOTHING
`

func (q *Queries) UpsertASNIncludeList(ctx context.Context, db DBTX, asn int64) error {
	_, err := db.ExecContext(ctx, upsertASNIncludeList, asn)
	return err
}

const upsertDomainIncludeList = `-- name: UpsertDomainIncludeList :exec
INSERT INTO domain_includelist (domain)
    VALUES (?1)
    ON CONFLICT (domain) DO NOTHING
`

func (q *Queries) UpsertDomainIncludeList(ctx context.Context, db DBTX, domain string) error {
	_, err := db.ExecContext(ctx, upsertDomainIncludeList, domain)
	return err
}

const upsertIPIncludeList = `-- name: UpsertIPIncludeList :exec
INSERT INTO ip_includelist (subnet)
    VALUES (?1)
    ON CONFLICT (subnet) DO NOTHING
`

func (q *Queries) UpsertIPIncludeList(ctx context.Context, db DBTX, subnet string) error {
	_, err := db.ExecContext(ctx, upsertIPIncludeList, subnet)
	return err
}

const upsertJA3IncludeList = `-- name: UpsertJA3IncludeList :exec
INSERT INTO ja3_includelist (hash)
    VALUES (?1)
    ON CONFLICT (hash) DO NOTHING
`

func (q *Queries) UpsertJA3IncludeList(ctx context.Context, db DBTX, hash string) error {
	_, err := db.ExecContext(ctx, upsertJA3IncludeList, hash)
	return err
}
