// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	GetAllASNExcludeList(ctx context.Context, db DBTX) ([]int64, error)
	GetAllASNIncludeList(ctx context.Context, db DBTX) ([]int64, error)
	GetAllCountryBlockList(ctx context.Context, db DBTX) ([]string, error)
	GetAllDomainExcludeList(ctx context.Context, db DBTX) ([]string, error)
	GetAllDomainIncludeList(ctx context.Context, db DBTX) ([]string, error)
	GetAllIPAllowList(ctx context.Context, db DBTX) ([]string, error)
	GetAllIPExcludeList(ctx context.Context, db DBTX) ([]string, error)
	GetAllIPIncludeList(ctx context.Context, db DBTX) ([]string, error)
	GetAllJA3ExcludeList(ctx context.Context, db DBTX) ([]string, error)
	GetAllJA3IncludeList(ctx context.Context, db DBTX) ([]string, error)
	RemoveASNExcludeList(ctx context.Context, db DBTX, asn int64) error
	RemoveASNIncludeList(ctx context.Context, db DBTX, asn int64) error
	RemoveCountryBlockList(ctx context.Context, db DBTX, country string) error
	RemoveDomainExcludeList(ctx context.Context, db DBTX, domain string) error
	RemoveDomainIncludeList(ctx context.Context, db DBTX, domain string) error
	RemoveIPAllowList(ctx context.Context, db DBTX, subnet string) error
	RemoveIPExcludeList(ctx context.Context, db DBTX, subnet string) error
	RemoveIPIncludeList(ctx context.Context, db DBTX, subnet string) error
	RemoveJA3ExcludeList(ctx context.Context, db DBTX, hash string) error
	RemoveJA3IncludeList(ctx context.Context, db DBTX, hash string) error
	UpsertASNExcludeList(ctx context.Context, db DBTX, asn int64) error
	UpsertASNIncludeList(ctx context.Context, db DBTX, asn int64) error
	UpsertCountryBlockList(ctx context.Context, db DBTX, country string) error
	UpsertDomainExcludeList(ctx context.Context, db DBTX, domain string) error
	UpsertDomainIncludeList(ctx context.Context, db DBTX, domain string) error
	UpsertIPAllowList(ctx context.Context, db DBTX, subnet string) error
	UpsertIPExcludeList(ctx context.Context, db DBTX, subnet string) error
	UpsertIPIncludeList(ctx context.Context, db DBTX, subnet string) error
	UpsertJA3ExcludeList(ctx context.Context, db DBTX, hash string) error
	UpsertJA3IncludeList(ctx context.Context, db DBTX, hash string) error
}

var _ Querier = (*Queries)(nil)
