// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cnaize/meds/src/database (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination=querier_mock.go -package=database . Querier
//

// Package database is a generated GoMock package.
package database

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// GetAllASNExcludeList mocks base method.
func (m *MockQuerier) GetAllASNExcludeList(ctx context.Context, db DBTX) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllASNExcludeList", ctx, db)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllASNExcludeList indicates an expected call of GetAllASNExcludeList.
func (mr *MockQuerierMockRecorder) GetAllASNExcludeList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllASNExcludeList", reflect.TypeOf((*MockQuerier)(nil).GetAllASNExcludeList), ctx, db)
}

// GetAllASNIncludeList mocks base method.
func (m *MockQuerier) GetAllASNIncludeList(ctx context.Context, db DBTX) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllASNIncludeList", ctx, db)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllASNIncludeList indicates an expected call of GetAllASNIncludeList.
func (mr *MockQuerierMockRecorder) GetAllASNIncludeList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllASNIncludeList", reflect.TypeOf((*MockQuerier)(nil).GetAllASNIncludeList), ctx, db)
}

// GetAllCountryBlockList mocks base method.
func (m *MockQuerier) GetAllCountryBlockList(ctx context.Context, db DBTX) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCountryBlockList", ctx, db)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCountryBlockList indicates an expected call of GetAllCountryBlockList.
func (mr *MockQuerierMockRecorder) GetAllCountryBlockList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCountryBlockList", reflect.TypeOf((*MockQuerier)(nil).GetAllCountryBlockList), ctx, db)
}

// GetAllDomainExcludeList mocks base method.
func (m *MockQuerier) GetAllDomainExcludeList(ctx context.Context, db DBTX) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDomainExcludeList", ctx, db)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDomainExcludeList indicates an expected call of GetAllDomainExcludeList.
func (mr *MockQuerierMockRecorder) GetAllDomainExcludeList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDomainExcludeList", reflect.TypeOf((*MockQuerier)(nil).GetAllDomainExcludeList), ctx, db)
}

// GetAllDomainIncludeList mocks base method.
func (m *MockQuerier) GetAllDomainIncludeList(ctx context.Context, db DBTX) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDomainIncludeList", ctx, db)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDomainIncludeList indicates an expected call of GetAllDomainIncludeList.
func (mr *MockQuerierMockRecorder) GetAllDomainIncludeList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDomainIncludeList", reflect.TypeOf((*MockQuerier)(nil).GetAllDomainIncludeList), ctx, db)
}

// GetAllIPAllowList mocks base method.
func (m *MockQuerier) GetAllIPAllowList(ctx context.Context, db DBTX) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIPAllowList", ctx, db)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllIPAllowList indicates an expected call of GetAllIPAllowList.
func (mr *MockQuerierMockRecorder) GetAllIPAllowList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIPAllowList", reflect.TypeOf((*MockQuerier)(nil).GetAllIPAllowList), ctx, db)
}

// GetAllIPExcludeList mocks base method.
func (m *MockQuerier) GetAllIPExcludeList(ctx context.Context, db DBTX) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIPExcludeList", ctx, db)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllIPExcludeList indicates an expected call of GetAllIPExcludeList.
func (mr *MockQuerierMockRecorder) GetAllIPExcludeList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIPExcludeList", reflect.TypeOf((*MockQuerier)(nil).GetAllIPExcludeList), ctx, db)
}

// GetAllIPIncludeList mocks base method.
func (m *MockQuerier) GetAllIPIncludeList(ctx context.Context, db DBTX) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIPIncludeList", ctx, db)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllIPIncludeList indicates an expected call of GetAllIPIncludeList.
func (mr *MockQuerierMockRecorder) GetAllIPIncludeList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIPIncludeList", reflect.TypeOf((*MockQuerier)(nil).GetAllIPIncludeList), ctx, db)
}

// GetAllJA3ExcludeList mocks base method.
func (m *MockQuerier) GetAllJA3ExcludeList(ctx context.Context, db DBTX) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllJA3ExcludeList", ctx, db)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllJA3ExcludeList indicates an expected call of GetAllJA3ExcludeList.
func (mr *MockQuerierMockRecorder) GetAllJA3ExcludeList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllJA3ExcludeList", reflect.TypeOf((*MockQuerier)(nil).GetAllJA3ExcludeList), ctx, db)
}

// GetAllJA3IncludeList mocks base method.
func (m *MockQuerier) GetAllJA3IncludeList(ctx context.Context, db DBTX) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllJA3IncludeList", ctx, db)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllJA3IncludeList indicates an expected call of GetAllJA3IncludeList.
func (mr *MockQuerierMockRecorder) GetAllJA3IncludeList(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllJA3IncludeList", reflect.TypeOf((*MockQuerier)(nil).GetAllJA3IncludeList), ctx, db)
}

// RemoveASNExcludeList mocks base method.
func (m *MockQuerier) RemoveASNExcludeList(ctx context.Context, db DBTX, asn int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveASNExcludeList", ctx, db, asn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveASNExcludeList indicates an expected call of RemoveASNExcludeList.
func (mr *MockQuerierMockRecorder) RemoveASNExcludeList(ctx, db, asn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveASNExcludeList", reflect.TypeOf((*MockQuerier)(nil).RemoveASNExcludeList), ctx, db, asn)
}

// RemoveASNIncludeList mocks base method.
func (m *MockQuerier) RemoveASNIncludeList(ctx context.Context, db DBTX, asn int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveASNIncludeList", ctx, db, asn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveASNIncludeList indicates an expected call of RemoveASNIncludeList.
func (mr *MockQuerierMockRecorder) RemoveASNIncludeList(ctx, db, asn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveASNIncludeList", reflect.TypeOf((*MockQuerier)(nil).RemoveASNIncludeList), ctx, db, asn)
}

// RemoveCountryBlockList mocks base method.
func (m *MockQuerier) RemoveCountryBlockList(ctx context.Context, db DBTX, country string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCountryBlockList", ctx, db, country)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCountryBlockList indicates an expected call of RemoveCountryBlockList.
func (mr *MockQuerierMockRecorder) RemoveCountryBlockList(ctx, db, country any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCountryBlockList", reflect.TypeOf((*MockQuerier)(nil).RemoveCountryBlockList), ctx, db, country)
}

// RemoveDomainExcludeList mocks base method.
func (m *MockQuerier) RemoveDomainExcludeList(ctx context.Context, db DBTX, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDomainExcludeList", ctx, db, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDomainExcludeList indicates an expected call of RemoveDomainExcludeList.
func (mr *MockQuerierMockRecorder) RemoveDomainExcludeList(ctx, db, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDomainExcludeList", reflect.TypeOf((*MockQuerier)(nil).RemoveDomainExcludeList), ctx, db, domain)
}

// RemoveDomainIncludeList mocks base method.
func (m *MockQuerier) RemoveDomainIncludeList(ctx context.Context, db DBTX, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDomainIncludeList", ctx, db, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDomainIncludeList indicates an expected call of RemoveDomainIncludeList.
func (mr *MockQuerierMockRecorder) RemoveDomainIncludeList(ctx, db, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDomainIncludeList", reflect.TypeOf((*MockQuerier)(nil).RemoveDomainIncludeList), ctx, db, domain)
}

// RemoveIPAllowList mocks base method.
func (m *MockQuerier) RemoveIPAllowList(ctx context.Context, db DBTX, subnet string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveIPAllowList", ctx, db, subnet)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveIPAllowList indicates an expected call of RemoveIPAllowList.
func (mr *MockQuerierMockRecorder) RemoveIPAllowList(ctx, db, subnet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveIPAllowList", reflect.TypeOf((*MockQuerier)(nil).RemoveIPAllowList), ctx, db, subnet)
}

// RemoveIPExcludeList mocks base method.
func (m *MockQuerier) RemoveIPExcludeList(ctx context.Context, db DBTX, subnet string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveIPExcludeList", ctx, db, subnet)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveIPExcludeList indicates an expected call of RemoveIPExcludeList.
func (mr *MockQuerierMockRecorder) RemoveIPExcludeList(ctx, db, subnet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveIPExcludeList", reflect.TypeOf((*MockQuerier)(nil).RemoveIPExcludeList), ctx, db, subnet)
}

// RemoveIPIncludeList mocks base method.
func (m *MockQuerier) RemoveIPIncludeList(ctx context.Context, db DBTX, subnet string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveIPIncludeList", ctx, db, subnet)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveIPIncludeList indicates an expected call of RemoveIPIncludeList.
func (mr *MockQuerierMockRecorder) RemoveIPIncludeList(ctx, db, subnet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveIPIncludeList", reflect.TypeOf((*MockQuerier)(nil).RemoveIPIncludeList), ctx, db, subnet)
}

// RemoveJA3ExcludeList mocks base method.
func (m *MockQuerier) RemoveJA3ExcludeList(ctx context.Context, db DBTX, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveJA3ExcludeList", ctx, db, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveJA3ExcludeList indicates an expected call of RemoveJA3ExcludeList.
func (mr *MockQuerierMockRecorder) RemoveJA3ExcludeList(ctx, db, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveJA3ExcludeList", reflect.TypeOf((*MockQuerier)(nil).RemoveJA3ExcludeList), ctx, db, hash)
}

// RemoveJA3IncludeList mocks base method.
func (m *MockQuerier) RemoveJA3IncludeList(ctx context.Context, db DBTX, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveJA3IncludeList", ctx, db, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveJA3IncludeList indicates an expected call of RemoveJA3IncludeList.
func (mr *MockQuerierMockRecorder) RemoveJA3IncludeList(ctx, db, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveJA3IncludeList", reflect.TypeOf((*MockQuerier)(nil).RemoveJA3IncludeList), ctx, db, hash)
}

// UpsertASNExcludeList mocks base method.
func (m *MockQuerier) UpsertASNExcludeList(ctx context.Context, db DBTX, asn int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertASNExcludeList", ctx, db, asn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertASNExcludeList indicates an expected call of UpsertASNExcludeList.
func (mr *MockQuerierMockRecorder) UpsertASNExcludeList(ctx, db, asn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertASNExcludeList", reflect.TypeOf((*MockQuerier)(nil).UpsertASNExcludeList), ctx, db, asn)
}

// UpsertASNIncludeList mocks base method.
func (m *MockQuerier) UpsertASNIncludeList(ctx context.Context, db DBTX, asn int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertASNIncludeList", ctx, db, asn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertASNIncludeList indicates an expected call of UpsertASNIncludeList.
func (mr *MockQuerierMockRecorder) UpsertASNIncludeList(ctx, db, asn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertASNIncludeList", reflect.TypeOf((*MockQuerier)(nil).UpsertASNIncludeList), ctx, db, asn)
}

// UpsertCountryBlockList mocks base method.
func (m *MockQuerier) UpsertCountryBlockList(ctx context.Context, db DBTX, country string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCountryBlockList", ctx, db, country)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCountryBlockList indicates an expected call of UpsertCountryBlockList.
func (mr *MockQuerierMockRecorder) UpsertCountryBlockList(ctx, db, country any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCountryBlockList", reflect.TypeOf((*MockQuerier)(nil).UpsertCountryBlockList), ctx, db, country)
}

// UpsertDomainExcludeList mocks base method.
func (m *MockQuerier) UpsertDomainExcludeList(ctx context.Context, db DBTX, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDomainExcludeList", ctx, db, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDomainExcludeList indicates an expected call of UpsertDomainExcludeList.
func (mr *MockQuerierMockRecorder) UpsertDomainExcludeList(ctx, db, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDomainExcludeList", reflect.TypeOf((*MockQuerier)(nil).UpsertDomainExcludeList), ctx, db, domain)
}

// UpsertDomainIncludeList mocks base method.
func (m *MockQuerier) UpsertDomainIncludeList(ctx context.Context, db DBTX, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDomainIncludeList", ctx, db, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDomainIncludeList indicates an expected call of UpsertDomainIncludeList.
func (mr *MockQuerierMockRecorder) UpsertDomainIncludeList(ctx, db, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDomainIncludeList", reflect.TypeOf((*MockQuerier)(nil).UpsertDomainIncludeList), ctx, db, domain)
}

// UpsertIPAllowList mocks base method.
func (m *MockQuerier) UpsertIPAllowList(ctx context.Context, db DBTX, subnet string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertIPAllowList", ctx, db, subnet)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertIPAllowList indicates an expected call of UpsertIPAllowList.
func (mr *MockQuerierMockRecorder) UpsertIPAllowList(ctx, db, subnet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertIPAllowList", reflect.TypeOf((*MockQuerier)(nil).UpsertIPAllowList), ctx, db, subnet)
}

// UpsertIPExcludeList mocks base method.
func (m *MockQuerier) UpsertIPExcludeList(ctx context.Context, db DBTX, subnet string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertIPExcludeList", ctx, db, subnet)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertIPExcludeList indicates an expected call of UpsertIPExcludeList.
func (mr *MockQuerierMockRecorder) UpsertIPExcludeList(ctx, db, subnet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertIPExcludeList", reflect.TypeOf((*MockQuerier)(nil).UpsertIPExcludeList), ctx, db, subnet)
}

// UpsertIPIncludeList mocks base method.
func (m *MockQuerier) UpsertIPIncludeList(ctx context.Context, db DBTX, subnet string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertIPIncludeList", ctx, db, subnet)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertIPIncludeList indicates an expected call of UpsertIPIncludeList.
func (mr *MockQuerierMockRecorder) UpsertIPIncludeList(ctx, db, subnet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertIPIncludeList", reflect.TypeOf((*MockQuerier)(nil).UpsertIPIncludeList), ctx, db, subnet)
}

// UpsertJA3ExcludeList mocks base method.
func (m *MockQuerier) UpsertJA3ExcludeList(ctx context.Context, db DBTX, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertJA3ExcludeList", ctx, db, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertJA3ExcludeList indicates an expected call of UpsertJA3ExcludeList.
func (mr *MockQuerierMockRecorder) UpsertJA3ExcludeList(ctx, db, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertJA3ExcludeList", reflect.TypeOf((*MockQuerier)(nil).UpsertJA3ExcludeList), ctx, db, hash)
}

// UpsertJA3IncludeList mocks base method.
func (m *MockQuerier) UpsertJA3IncludeList(ctx context.Context, db DBTX, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertJA3IncludeList", ctx, db, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertJA3IncludeList indicates an expected call of UpsertJA3IncludeList.
func (mr *MockQuerierMockRecorder) UpsertJA3IncludeList(ctx, db, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertJA3IncludeList", reflect.TypeOf((*MockQuerier)(nil).UpsertJA3IncludeList), ctx, db, hash)
}
