// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whitelist.sql

package database

import (
	"context"
)

const getWhitelistAllSubnets = `-- name: GetWhitelistAllSubnets :many
SELECT subnet FROM sn_whitelist
`

func (q *Queries) GetWhitelistAllSubnets(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getWhitelistAllSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subnet string
		if err := rows.Scan(&subnet); err != nil {
			return nil, err
		}
		items = append(items, subnet)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
