// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whitelist.sql

package database

import (
	"context"
)

const getAllWhiteListSubnets = `-- name: GetAllWhiteListSubnets :many
SELECT subnet FROM subnet_whitelist
`

func (q *Queries) GetAllWhiteListSubnets(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAllWhiteListSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subnet string
		if err := rows.Scan(&subnet); err != nil {
			return nil, err
		}
		items = append(items, subnet)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWhiteListSubnet = `-- name: RemoveWhiteListSubnet :exec
DELETE FROM subnet_whitelist
WHERE subnet = ?1
`

func (q *Queries) RemoveWhiteListSubnet(ctx context.Context, db DBTX, subnet string) error {
	_, err := db.ExecContext(ctx, removeWhiteListSubnet, subnet)
	return err
}

const upsertWhiteListSubnet = `-- name: UpsertWhiteListSubnet :exec
INSERT INTO subnet_whitelist (subnet)
VALUES (?1)
`

func (q *Queries) UpsertWhiteListSubnet(ctx context.Context, db DBTX, subnet string) error {
	_, err := db.ExecContext(ctx, upsertWhiteListSubnet, subnet)
	return err
}
